AttendanceCheckerSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AttendanceCheckerSystem.Data;
using AttendanceCheckerSystem.Models;

namespace AttendanceCheckerSystem.Controllers
{
    public class HomeController : Controller
    {

        private readonly ApplicationDbContext _context;

        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Meetings
        public async Task<IActionResult> Index()
        {

            var days = await _context.Meetings.ToListAsync();
            var students = await _context.Students.ToListAsync();

            var meetings = days.OrderBy(d => d.MeetingDay);
            ViewData["MeetingList"] = meetings;

            var studentsSorted = students.OrderBy(s => s.LastName);
            ViewData["StudentList"] = studentsSorted;
            
            return View();
        }


        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AttendanceCheckerSystem/Controllers/MeetingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AttendanceCheckerSystem.Data;
using AttendanceCheckerSystem.Models;

namespace AttendanceCheckerSystem.Controllers
{
    public class MeetingsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MeetingsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Meetings
        public async Task<IActionResult> Index()
        {

            var days = await _context.Meetings.ToListAsync();
            var sorteddays = days.OrderBy(d => d.MeetingDay);

            return View(sorteddays);
        }

        public IActionResult SearchStudents()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SearchResults(SearchInputModel search)
        {

            var students = await _context.Students.ToListAsync();

            var filtered = students.Where(s => s.LastName == search.SearchLastName ||
                                          s.FirstName == search.SearchFirstName);

            return View(filtered);
        }
        [HttpPost, ActionName("Attend")]
        public IActionResult StudentAttends(AttendanceViewModel vm)
        {

            var selectedList = _context.AttendMeeting.Where(m => m.MeetingID == vm.MeetingID &&
                                                             m.StudentID == vm.StudentID);

            var selected = _context.AttendMeeting.Find(selectedList.First().ID);

            selected.Attend = true;

            _context.SaveChanges();

            return RedirectToAction("StudentAttendanceConfirmed", vm);
            //return View("StudentAttendanceConfirmed", selected);
        }

        public async Task<IActionResult> StudentAttendanceConfirmed(AttendanceViewModel attended)
        {
            var days = await _context.Meetings.ToListAsync();
            var students = await _context.Students.ToListAsync();

            var meetings = days.OrderBy(d => d.MeetingDay);
            ViewData["MeetingList"] = meetings;

            var studentsSorted = students.OrderBy(s => s.LastName);
            ViewData["StudentList"] = studentsSorted;

            var student = students.Where(s => s.ID == attended.StudentID).First();
            var meeting = meetings.Where(m => m.ID == attended.MeetingID).First();

            StudentAttendanceConfirmedViewModel vm = new StudentAttendanceConfirmedViewModel
            {
                StudentName = student.LastName + ", " + student.FirstName,
                DateAttended = meeting.MeetingDay
            };

            return View(vm);
        }

        public async Task<IActionResult> AttendanceSummary()
        {
            IEnumerable<Student> list = await _context.Students.ToListAsync();

            //var filtered_list = list.Where(s => s.FirstName.StartsWith("Ja"));

            var filtered_list = from s in list
                                where s.FirstName.StartsWith("")
                                select s;


            return View(filtered_list);
        }


        // GET: Meetings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meetings
                .SingleOrDefaultAsync(m => m.ID == id);
            if (meeting == null)
            {
                return NotFound();
            }

            ViewData["MeetingInfo"] = meeting.MeetingDay.ToLongDateString();


            var model = _context.Students
                .Join(_context.AttendMeeting,
                      s => s.ID,
                      a => a.StudentID,
                      ((student, attend) => new AttendanceDetailViewModel { Student = student, Attend = attend }))
                .Where(m => m.Attend.MeetingID == meeting.ID)
                .OrderBy(m => m.Student.LastName);

            return View(model);
        }

        // GET: Meetings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Meetings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,MeetingTimes,MeetingDay,MeetingLocation")] Meeting meeting)
        {
            if (ModelState.IsValid)
            {
                _context.Add(meeting);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(meeting);
        }

        // GET: Meetings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meetings.SingleOrDefaultAsync(m => m.ID == id);
            if (meeting == null)
            {
                return NotFound();
            }
            return View(meeting);
        }

        // POST: Meetings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,MeetingTimes,MeetingDay,MeetingLocation")] Meeting meeting)
        {
            if (id != meeting.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(meeting);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MeetingExists(meeting.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(meeting);
        }

        // GET: Meetings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meetings
                .SingleOrDefaultAsync(m => m.ID == id);
            if (meeting == null)
            {
                return NotFound();
            }

            return View(meeting);
        }

        // POST: Meetings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var meeting = await _context.Meetings.SingleOrDefaultAsync(m => m.ID == id);
            _context.Meetings.Remove(meeting);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MeetingExists(int id)
        {
            return _context.Meetings.Any(e => e.ID == id);
        }
    }
}

AttendanceCheckerSystem/Views/Home/About.cshtml
@{
    ViewData["Title"] = "CIDM 3312 01";
}
<h2>CIDM 3312 01</h2>
<p><a href="/attendance/?rm=sum&amp;u=CIDM&amp;n=3312&amp;e=01">Click here for an attendance summary for this course</a></p>
<ul>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377487"><span class="mdate">Monday 28 August 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377488"><span class="mdate">Wednesday 30 August 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377489"><span class="mdate">Wednesday 06 September 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377490"><span class="mdate">Monday 11 September 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377491"><span class="mdate">Wednesday 13 September 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377492"><span class="mdate">Monday 18 September 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377493"><span class="mdate">Wednesday 20 September 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377494"><span class="mdate">Monday 25 September 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377495"><span class="mdate">Wednesday 27 September 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377496"><span class="mdate">Monday 02 October 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377497"><span class="mdate">Wednesday 04 October 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377498"><span class="mdate">Monday 09 October 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377499"><span class="mdate">Wednesday 11 October 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377500"><span class="mdate">Monday 16 October 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377501"><span class="mdate">Wednesday 18 October 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377502"><span class="mdate">Monday 23 October 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377503"><span class="mdate">Wednesday 25 October 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377504"><span class="mdate">Monday 30 October 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377505"><span class="mdate">Wednesday 01 November 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377506"><span class="mdate">Monday 06 November 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377507"><span class="mdate">Wednesday 08 November 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377508"><span class="mdate">Monday 13 November 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377509"><span class="mdate">Wednesday 15 November 2017</span> CC205</a></li>
    <li><a href="/attendance/?rm=a&amp;u=CIDM&amp;n=3312&amp;e=01&amp;i=2377510"><span class="mdate">Monday 20 November 2017</span> CC205</a></li>
    <li><span class="mdate">Monday 27 November 2017</span> CC205</li>
    <li><span class="mdate">Wednesday 29 November 2017</span> CC205</li>
    <li><span class="mdate">Monday 04 December 2017</span> CC205</li>
    <li><span class="mdate">Wednesday 06 December 2017</span> CC205</li>
</ul>

AttendanceCheckerSystem/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AttendanceCheckerSystem/Views/Home/Index.cshtml
@model AttendanceViewModel
@{
    ViewData["Title"] = "Home Page";

    List<SelectListItem> meetingDropdownData = new List<SelectListItem>();

    var meetingList = (IEnumerable<Meeting>)ViewData["MeetingList"];
    foreach (var day in meetingList)
    {
        meetingDropdownData.Add(new SelectListItem()
        {
            Text = day.MeetingDay.ToLongDateString(),
            Value = day.ID.ToString()
        });
    }

    List<SelectListItem> studentDropdownData = new List<SelectListItem>();

    var studentList = (IEnumerable<Student>)ViewData["StudentList"];
    foreach (var student in studentList)
    {
        studentDropdownData.Add(new SelectListItem()
        {
            Text = student.LastName + ", " + student.FirstName,
            Value = student.ID.ToString()
        });
    }

}

<div>
    <div>
        <h2>Today is: @DateTime.Now.ToLocalTime().ToLongDateString()</h2>
    </div>
    <form asp-controller="Meetings" asp-action="Attend" method="post">
        @Html.DropDownListFor(s => s.StudentID, studentDropdownData)
        <br />
        @Html.DropDownListFor(m => m.MeetingID, meetingDropdownData)
        <br />
        <input type="submit" value="submit" title="Attend" />
    </form>
</div>